const BOOKABLE_RECEIVE_BOOKABLES_FOR_QUERY = 'BOOKABLE_RECEIVE_BOOKABLES_FOR_QUERY';
const BOOKABLE_RECEIVE_BOOKABLE = 'BOOKABLE_RECEIVE_BOOKABLE';

export default {BOOKABLE_RECEIVE_BOOKABLES_FOR_QUERY, BOOKABLE_RECEIVE_BOOKABLE};
