import GlobalConstants from "./GlobalConstants";

const BOOKING_RECEIVE_BOOKINGS_FOR_QUERY = 'BOOKING_RECEIVE_BOOKINGS_FOR_QUERY';
const BOOKING_RECEIVE_BOOKING = 'BOOKING_RECEIVE_BOOKING';
const BOOKING_RECEIVE_CREATE_ERRORS = 'BOOKING_RECEIVE_CREATE_ERRORS';
const BOOKING_RECEIVE_BOOKING_DESTROYED = 'BOOKING_RECEIVE_BOOKING_DESTROYED';

const AWAITING_APPROVAL_RECEIVE_RAW = 'AWAITING_APPROVAL_RECEIVE_RAW';
const AWAITING_APPROVAL_REFRESH_INTERVAL = 10 * GlobalConstants.MINUTES;

export default {
	BOOKING_RECEIVE_BOOKINGS_FOR_QUERY,
	BOOKING_RECEIVE_BOOKING,
	BOOKING_RECEIVE_CREATE_ERRORS,
	BOOKING_RECEIVE_BOOKING_DESTROYED,
	AWAITING_APPROVAL_RECEIVE_RAW,
	AWAITING_APPROVAL_REFRESH_INTERVAL
};
