const BOOKINGPART_RECEIVE_BOOKINGPARTS_FOR_BOOKABLE = 'BOOKINGPART_RECEIVE_BOOKINGPARTS_FOR_BOOKABLE';
const BOOKINGPART_RECEIVE_BOOKINGPARTS_FOR_BOOKING = 'BOOKINGPART_RECEIVE_BOOKINGPARTS_FOR_BOOKING';
const BOOKINGPART_RECEIVE_BOOKINGPART = 'BOOKINGPART_RECEIVE_BOOKINGPART';
const BOOKINGPART_RECEIVE_CREATE_ERRORS = 'BOOKINGPART_RECEIVE_CREATE_ERRORS';
const BOOKINGPART_RECEIVE_BOOKINGPART_DESTROYED = 'BOOKINGPART_RECEIVE_BOOKINGPART_DESTROYED';

export default {
	BOOKINGPART_RECEIVE_BOOKINGPARTS_FOR_BOOKABLE,
	BOOKINGPART_RECEIVE_BOOKINGPARTS_FOR_BOOKING,
	BOOKINGPART_RECEIVE_BOOKINGPART,
	BOOKINGPART_RECEIVE_CREATE_ERRORS,
	BOOKINGPART_RECEIVE_BOOKINGPART_DESTROYED
};
